# Generated by Django 5.0.6 on 2024-10-01 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_tipoassento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Filme",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=255)),
                ("duracao", models.IntegerField()),
                ("dataLancamento", models.IntegerField()),
                ("sinopse", models.TextField()),
                ("trailer", models.URLField(blank=True, null=True)),
                ("categoria", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.categoria")),
            ],
        ),
    ]
