# Generated by Django 5.0.6 on 2024-10-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_filme"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sala",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numeroAssentos", models.IntegerField(default=0)),
                ("numeroSala", models.IntegerField(default=0)),
            ],
        ),
    ]
