# Generated by Django 5.0.6 on 2024-10-09 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_sala"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numeroAssento", models.IntegerField(default=0)),
                ("fileira", models.CharField(max_length=1)),
                ("sala", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.sala")),
                ("tipoAssento", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.tipoassento")),
            ],
        ),
    ]
