# Generated by Django 5.0.6 on 2024-10-09 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_assento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sessao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("horario", models.DateTimeField()),
                ("filme", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.filme")),
                ("sala", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.sala")),
            ],
        ),
    ]
