# Generated by Django 5.0.6 on 2024-10-09 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_sessao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filme",
            name="categoria",
        ),
        migrations.CreateModel(
            name="Ingresso",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo", models.IntegerField(unique=True)),
                ("tipo", models.BooleanField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=5)),
                ("sessao", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.sessao")),
            ],
        ),
        migrations.AddField(
            model_name="filme",
            name="categoria",
            field=models.ManyToManyField(to="core.categoria"),
        ),
    ]
