# Generated by Django 5.0.6 on 2024-12-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_carrinho_user_carrinho"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="passage_id",
        ),
    ]
