# Generated by Django 5.0.6 on 2024-12-06 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_user_passage_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingresso",
            name="sessao",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.sessao"),
        ),
    ]
